---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_IMAGE:-docker.io/ihmels/docker-fedora35-ansible:latest}"
    pre_build_image: true
provisioner:
  name: ansible
